### ISSUE TITLE
xcode 8 has problem to use WYMaterialButton

### ISSUE THREAD

**Issue by amoghpalnitkar** [Yu-w/WYMaterialButton#3]
Hi I'm using the storyboard.

I got an error like this.

file:///Users/{user}/Documents/{dir}/{dir}/Base.lproj/CheckOut.storyboard: error: IB Designables: Failed to render and update auto layout status for CheckoutViewController (cXb-N2-E0w): dlopen(WYMaterialButton.framework, 1): Library not loaded: @rpath/pop.framework/pop
  Referenced from: WYMaterialButton.framework
  Reason: image not found

Anyone knows about this problem? 
My xcode version is 8.1, using swift 2.3

**Comment by Yu-w** [comment]
Please update to Swift 3 and the problem should be solved~
